name: Schedule workflow
on:
  schedule:
    - cron: "12 21 * * *"
jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: schedule game
        run: echo "hey dost , schedule workflow is done"
